### ISSUE TITLE
Swift 3 update?

### ISSUE THREAD

**Issue by farazhaider88** [kwandrews7/MultiDirectionCollectionView#1]
can you please update your code on swift3?

**Comment by kwandrews7** [comment]
Hi @farazhaider88 thanks for the comment. I'm fairly booked up this week, but I can likely get a Swift 3 update published this weekend. I'll comment and close this issue once it's published.

**Comment by farazhaider88** [comment]
That will be great :) thanks im waiting for this.

**Comment by kwandrews7** [comment]
@farazhaider88 master branch updated.

**Comment by L-Jovi** [comment]
@kwandrews7  ohhhh!  thanks for your swift 3.0 update!!  love you :)
