### ISSUE TITLE
how can i calculate cell height and width dynamically?

### ISSUE THREAD

**Issue by farazhaider88** [kwandrews7/MultiDirectionCollectionView#2]
Hi ,

In your example you are hardcoding the cell height and width by doing this:

    let CELL_HEIGHT = 30.0
    let CELL_WIDTH = 100.0

is there any way that cell height and width can be calculated directly? means cell calculate its size with the help of content.

**Comment by farazhaider88** [comment]
??

**Comment by kwandrews7** [comment]
Yes, there is a way. The project in which we used this setup was a TV guide where the height was always static but the width was variable based on the length of the program. Those variables can be manipulated in any way you see fit. Where the variables `CELL_HEIGHT` and `CELL_WIDTH` are used in the layout, you can change your code to pull those numbers from any data source or calculation you choose. The process for building something like that out is a little beyond the tutorial blog and sample I've created.

To get you going, first determine how you want to calculate your size, then replace any references to the variables CELL_HEIGHT and CELL_WIDTH with references to a function, data source, or variable that will calculate your new size. If the calculations are processor intensive, you may very well want to look into doing your calculations ahead of time and just providing the CGRect pre-built to the layout class. This can keep your view from feeling jittery.
